name: CI

on:
  pull_request:
  push:

jobs:
  test:
    name: macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - run: cargo check
      - run: cargo test
      - run: cargo build --release
